#!/bin/bash

export $(xargs < .env)

BASE_URL="https://boisestatecanvas.instructure.com"

RED="\u001b[31m"
GREEN="\u001b[32m"
YELLOW="\u001b[33m"
BLUE="\u001b[34m"
RESET="\u001b[0m"

get_courses_json(){
    curl -s \
        -H "Authorization: Bearer $CANVAS_API_TOKEN" \
        "$BASE_URL/api/v1/users/self/courses?enrollment_state=active&per_page=100"
}

get_assignments_json(){
    curl -s -G \
        -H "Authorization: Bearer $CANVAS_API_TOKEN" \
        "$BASE_URL/api/v1/courses/$1/assignments"
}

display_courses(){
    jq -r '
    if type == "object" and .errors then
        "\u001b[31m❌ Error: \(.errors[0].message)\u001b[0m"
    else
        .[] | select(.name) |
        (if .name | contains("Sp26") then "\u001b[32m" else "\u001b[37m" end) as $nameColor |

        "\u001b[36m\(.id)\u001b[0m\t\($nameColor)\(.name)\u001b[0m"
    end'
}

display_assignments(){
    jq -r '
    if type == "object" and .errors then
        "\u001b[31m❌ Error: \(.errors[0].message)\u001b[0m"
    else
        sort_by(.due_at) | .[] |

        (.due_at | fromdateiso8601? // 0) as $due_ts |
        (now) as $now_ts |

        (if $due_ts == 0 then "\u001b[37m"          # White (No due date)
         elif $due_ts < $now_ts then "\u001b[31m"   # Red (Overdue)
         elif $due_ts < ($now_ts + 86400) then "\u001b[33m" # Yellow (Due < 24h)
         else "\u001b[32m"                          # Green (Safe)
         end) as $color |

        "\($color)[\(.due_at // "    No Date    " | .[0:10])]\u001b[0m \t \u001b[36m(\(.points_possible // 0)pts)\u001b[0m \t \(.name)"
    end'
}

OPERATION="$1"
COURSE_ID="$2"

case "$OPERATION" in
    courses)
        get_courses_json | display_courses
        ;;
    assignments)
        get_assignments_json "$COURSE_ID" | display_assignments
        ;;
    *)
        echo "Usage: canvas_cli <operation> [<class-id>]" >&2
        echo "" >&2
        echo "Operations:" >&2
        echo "courses       Get the list of courses and their IDs." >&2
        echo "assignments   Get the list of assignments for a particular course." >&2
        echo ""
        exit 1
        ;;
esac

